- id: "scrots"
  name: "Update Scrots"
  entry: scrot_viewer/gen_scrot_paths
  # types: [paths]
  # exclude: ".yaml$|.yml$"
  language: "script"
  description: "Saves pathNames to a json file to load images in the scrot_viewer"
  # args: [--example1, --example2]